server:
  port: 8081
  servlet:
    context-path: /identity-service

spring:
  datasource:
#    url: jdbc:mysql://localhost:3307/identity_service
#    username: root
#    password: huyhieu
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:sqlserver://localhost:1433;databaseName=identity_service
    username: sa
    password: MyStrong!Passw0rd
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.SQLServerDialect

jwt:
  signer-key: "bwK6dJn4tdSpuG?XRR4iTrDNMwFaQScXy5zxJsfAy/d2aq-f7UpKHTe?PPha9v0O"
#logging:
#  level:
#    org.springframework: DEBUG
#    org.hibernate: DEBUG
