version: '3.8'

services:
  mysql-container:
    image: mysql:8.0.36-debian
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: huyhieu
      MYSQL_USER: huyhieu
      MYSQL_PASSWORD: huyhieu
    ports:
      - "3307:3306"
    networks:
      - my_network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data:
