version: '3.8'

services:
  sqlserver-container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MyStrong!Passw0rd
    ports:
      - "1433:1433"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
