version: '3.8'

services:
  sqlserver-container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1434:1433"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
